using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using BuildingBlocks.Application;

namespace Easebnb.WebApi;

/// <summary>
///     Extracts the current authenticated user from HttpContext claims.
///     Works with JWT tokens generated by JwtService (sub, unique_name, email claims).
/// </summary>
public class CurrentUserAccessor(IHttpContextAccessor httpContextAccessor) : ICurrentUserAccessor
{
    public bool IsAuthenticated =>
        httpContextAccessor.HttpContext?.User.Identity?.IsAuthenticated ?? false;

    public CurrentUser? GetCurrentUser()
    {
        var user = httpContextAccessor.HttpContext?.User;
        if (user?.Identity?.IsAuthenticated != true)
            return null;

        var userIdClaim = user.FindFirstValue(JwtRegisteredClaimNames.Sub)
                          ?? user.FindFirstValue(ClaimTypes.NameIdentifier);

        if (string.IsNullOrEmpty(userIdClaim) || !Guid.TryParse(userIdClaim, out var userId))
            return null;

        var userName = user.FindFirstValue(JwtRegisteredClaimNames.UniqueName)
                       ?? user.FindFirstValue(ClaimTypes.Name)
                       ?? string.Empty;

        var emailClaim = user.FindFirstValue(JwtRegisteredClaimNames.Email)
                         ?? user.FindFirstValue(ClaimTypes.Email);

        EmailAddress? email = null;
        if (!string.IsNullOrEmpty(emailClaim))
            email = new EmailAddress(emailClaim);

        return new CurrentUser
        {
            Id = new UserId(userId),
            UserName = userName,
            Email = email!
        };
    }

    public CurrentUser GetRequiredCurrentUser()
    {
        return GetCurrentUser()
               ?? throw new UnauthorizedAccessException("User is not authenticated.");
    }
}