<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>38b47871-ea37-4479-a3d3-12349248f2d9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks\BuildingBlocks.Endpoints\BuildingBlocks.Endpoints.csproj" />
        <ProjectReference Include="..\Modules\Identity\Easebnb.Identity.Application\Easebnb.Identity.Core.csproj" />
        <ProjectReference Include="..\Modules\Identity\Easebnb.Identity.Infrastructure\Easebnb.Identity.Infrastructure.csproj" />
        <ProjectReference Include="..\Easebnb.ServiceDefaults\Easebnb.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
