services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: easebnb-rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
      
  postgres:
    image: postgres:18-alpine3.23
    container_name: easebnb-postgres
    environment:
      POSTGRES_DB: easebnb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  rabbitmq_data:
  postgres_data: