<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.5.10"/>
        <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Database\Easebnb.Database\Easebnb.Database.csproj"/>
        <ProjectReference Include="..\Easebnb.Organization.Application\Easebnb.Organization.Application.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.IntegrationEvents\BuildingBlocks.IntegrationEvents.csproj"/>
    </ItemGroup>

</Project>
