<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\Database\Easebnb.Database\Easebnb.Database.csproj"/>
        <ProjectReference Include="..\Easebnb.Identity.Core\Easebnb.Identity.Core.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.IntegrationEvents\BuildingBlocks.IntegrationEvents.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Apis.Auth" Version="1.75.0"/>
        <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.10"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0"/>
    </ItemGroup>

</Project>
